image: archlinux
packages:
  - sed
  - make
  - coreutils
sources:
  - https://git.sr.ht/~kskeigrshi/to-arch.sh
secrets:
  - 520ca5eb-17ad-4a0b-8b08-313dc8450654
artifacts:
  - to-arch.sh/to-arch.sh
  
tasks:
  - build: |
      set +xe
      cd to-arch.sh
      make
  - pushtogithub: |
      set +xe
      cd to-arch.sh
      git switch master
      git push -f https://$(cat ~/.github_token)@github.com/kskeigrshi/to-arch.sh.git
      cd ..
      shred -u .github_token
